SELECT D.ID, A.FISH_NAME, C.MAX_LENGTH AS LENGTH
FROM FISH_NAME_INFO AS A
JOIN (
    SELECT B.FISH_TYPE, MAX(B.LENGTH) AS MAX_LENGTH
    FROM FISH_INFO AS B
    GROUP BY B.FISH_TYPE
) AS C
ON A.FISH_TYPE = C.FISH_TYPE
JOIN FISH_INFO AS D
ON D.FISH_TYPE = C.FISH_TYPE AND D.LENGTH = C.MAX_LENGTH 
;
